### ISSUE TITLE
Support Firebase security rules

### ISSUE THREAD

**Issue by azell** [urish/firebase-server#11]
It might be useful to integrate https://github.com/goldibex/targaryen with firebase-server.  Need to investigate whether this is possible.

**Comment by urish** [comment]
Great idea, thanks!

I have implemented some basic integration, which allows you to specify rules by calling the `setRules()` method on the server instance. Then, subsequent read and writes are validated against the rules.

Since we have no authentication support, this only works with unauthenticated rules, which is mostly useful for checking `.validate` rules.

**Comment by azell** [comment]
OK, I will look into the auth feature while you are looking at the rules engine,

**Comment by urish** [comment]
Great, thanks Adam!
