### ISSUE TITLE
can't login with custom token

### ISSUE THREAD

**Issue by slootzky** [urish/firebase-server#117]
I do as readme says

```
global.firebaseServer.setAuthSecret('TEST');
var tokenGenerator = new FirebaseTokenGenerator('TEST');
```
where tokenGenerator is `firebase-token-generator`

I then trying to `signInWithCustomToken` using Firebase's sdk and get `auth/invalid-custom-token` (error message is "failed to sign in to firebase")

can someone please explain how can I use `signInWithCustomToken` with firebase-server?

**Comment by jasonlfunk** [comment]
Yes, I'm also needing an answer to this question. I have the firebase-server running and have generated a token to use. However, when I try to use it on the client, it posts to google trying to verify the token.

`https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken?key=testing`

I don't understand how to use this library with any sort of authentication.

**Comment by urish** [comment]
This is not officially supported, however - if you do find a way, please document it here - or better, send a PR updating our README.

You can check out #94 or #81 as they might provide some ideas where to start. Finally, since the firebase client library is open sourced, you check out their implementation, and try to figure it out from there.
