### ISSUE TITLE
What are the difference with the real online Firebase service ?

### ISSUE THREAD

**Issue by chris2324** [urish/firebase-server#35]
What are the difference with the online service Firebase ?
Does it completely emulate the firebase server ?
Can it be use in local ?
Can we use it for a product, or do infringe license an copyright of Firebase co ?

**Comment by urish** [comment]
Hi, this project is intended to be a non-official, local, *in memory* firebase server. It tries to emulate the official fire base server as much as possible, but there could be some subtle difference (different behavior on concurrent access, differences in error messages).

Since all the data is stored in memory, it is usually not usable for production, though, I guess you can add some layer of persistence.

Not sure which copyright you are referring to - the project itself is `MIT` licensed, but it depends on the official Firebase javascript client, and I am not sure about its license. It would be best to reach the Firebase support team with this question
