### ISSUE TITLE
Using in iOS (Swift) app

### ISSUE THREAD

**Issue by galvezz** [urish/firebase-server#49]
Hello, the server is running all right on my laptop and javascript code can write and read data. However, when trying to access from Swift code is crashing. I have not researched well, just a quick research if somebody has made it work with Firebase Swift (Pod). thanks!

**Comment by urish** [comment]
Hi @galvezz, have you had any chance to research?

**Comment by galvezz** [comment]
Hi @urish . No, Sorry I have not had chance to continue, also, I found some Internet connections where I was missing to test.

**Comment by urish** [comment]
Okay, thanks for the speedy response!

 I will close this for now - if it still happens, and you have additional info, feel free to reopen.

**Comment by danielblx** [comment]
Hey! I'm trying to connect the iOS Firebase sdk with my custom server, but i got:

 *** Terminating app due to uncaught exception 'FirebaseInternalError', reason: 'For a custom Firebase host, you must first set your authentication server before using authentication features!'

Where can i setup in SDK with custom authentication server?
