### ISSUE TITLE
WebSocket connection to 'ws://test.firebaseio.com:5000/.ws?v=5' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by rehmsen** [urish/firebase-server#7]
This may just be me holding it wrong:
Connecting to the local firebase_server works fine from the nodejs client, but fails with the error above in the browser (Chromium Version 43.0.2357.130 Ubuntu 14.04 (64-bit)).

Firebase browser client version: 2.2.9
Firebase node client version: 2.2.7
Firebase-server version: 0.3.0

Firebase server:
```javascript
var FirebaseServer = require('firebase-server');
var fs = require('fs');
var data = JSON.parse(fs.readFileSync('firebase_data.json', 'utf-8'));
FirebaseServer.enableLogging(true);
new FirebaseServer(5000, 'test.firebaseio.com', data);
```

/etc/hosts:
```
127.0.0.1       test.firebaseio.com
```

Firebase browser client:
```javascript
new Firebase('ws://test.firebaseio.com:5000')
```

Error, every second in the Chrome console:
> WebSocket connection to 'ws://test.firebaseio.com:5000/.ws?v=5' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
Firebase server debug output
> [firebase-server] Listening for connections on port 5000

As I mentioned, the connection from node works fine. Debug output:
> [firebase-server] New connection from 127.0.0.1:54567
> ...

Any idea?

**Comment by urish** [comment]
Interesting, perhaps you need to restart your browser after editing the hosts file?

Another thing you can try is to use the following url instead: `ws://127.0.1:5000` in your client, as far as I recall, this tricks works in the browser (but not in node.js).

**Comment by urish** [comment]
Please re-open the issue if the above solutions didn't help

**Comment by rehmsen** [comment]
For posterity, restarting the browser did not work, but ws://127.0.1:5000 did work. Thanks @urish.

**Comment by urish** [comment]
:-)

**Comment by pavellishin** [comment]
Did anyone ever figure out *why* this happens?

**Comment by rosendi** [comment]
Same problem. `ws://127.0.1:5000` doesn't work since firebase forces to use` firebaseio.com `:
 
`Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com`

**Comment by urish** [comment]
You need just one zero in the middle, e.g. `ws://127.0.1:5000/`

**Comment by pavellishin** [comment]
@urish Sure, but that's weird, and not obvious, and not documented, and it took me some googling to find it.

**Comment by jamestalmage** [comment]
This discussion is a strong case for implementing #30.

**Comment by urish** [comment]
Agreed, however 127.0.1 is a hack and doesn't work in all environments (e.gg node), so I'd rather not document it. #30 should help, and I will also ping the Firebase team to see if they can introduce a small change in the client library to facilitate connecting to firebase-server.

For now, the recommended approach is to add a mapping between l`ocalhost.firebaseio.com` and 127.0.0.1 to your hosts file, add outlined in the README.

**Comment by rosendi** [comment]
@urish thank you!

**Comment by prust** [comment]
FYI, the `127.0.1` hack *does not work on Windows*! It took us far too long to figure out that that was causing our Windows build to fail.

Rather than modify the hosts file (which we were reticent to do, since we have a complicated build environment that involves multiple docker containers, etc), we opted to hack the non-minified `firebase-debug.js` file from https://github.com/firebase/firebase-bower by commenting out these lines:

```javascript
if (!namespace || namespace == "undefined") {
   fb.core.util.fatal("Cannot parse Firebase url. " + "Please use https://<YOUR FIREBASE>.firebaseio.com");	
}
```

Using this file from node also required changing `NODE_CLIENT = false;` to `NODE_CLIENT = true;` and it introduced a globals/isolation problem between the firebase client and server, such that we had to spawn a separate node process for the firebase server.

Not that I necessarily recommend this, but I wanted to document it to save others the trouble. For the long term, we hope to finish our conversion away from the firebase client library to their REST/SSE api and, from there, migrate away from Firebase entirely.

**Comment by urish** [comment]
@prust as far as I tested, `127.0.1` trick should work on Windows when using Chrome. Which setup do you use?

**Comment by prust** [comment]
@urish: We didn't use Chrome; we were using the node firebase client to connect to the firebase server to test a node app (both running in the same process, using mocha as the test runner).

**Comment by urish** [comment]
@prust yes, the workaround doesn't apply to NodeJS on windows, good to know it does work on OSX.

Have you found a solution for windows?

**Comment by prust** [comment]
@urish:

> Have you found a solution for windows?

Yes, I forked the firebase client and made it permissive about IP-address URLs (`127.0.0.1`). In an earlier comment I mentioned commenting out the 3-line guard, but it turned out that instead I needed a deeper, smaller change:

I changed this: `if (parts.length === 3) {`

To this: `if (parts.length >= 3) {`

You can see the changes here: https://github.com/CSNW/firebase-bower/commit/33e974c and can pull in the modified version by using this in package.json:

```javascript
"firebase": "git+https://github.com/CSNW/firebase-bower.git#v2.3.2-permissive-url-parsing",
```

**Comment by DonaldBough** [comment]
Would also like to comment that I had to find this fix after experiencing the same issue in 2019. I guess the good old Google will have to do 😉
