### ISSUE TITLE
Firebase Functions

### ISSUE THREAD

**Issue by navarrorc** [urish/firebase-server#93]
Can this server work with Functions. I just learned about them and know how to deploy them to the production instance. Would you have any examples on how to do this using the test server? Thanks!

**Comment by prescottprue** [comment]
@navarrorc I was wondering the same thing, and started trying to play with it myself. I didn't spend too long on it, but seems like it could be done relatively easily.

My plan was to mirror [firebase's instructions on how to unit test ](https://firebase.google.com/docs/functions/unit-testing) and pass `firebase-server` when stubbing to events to simplify stuff. After looking at it for a while though, not sure that using `firebase-server` along with it is even necessary, since in the example they do a full mock (instead of a "fake" server).

Firebase made [a local emulator for functions](https://firebase.google.com/docs/functions/local-emulator). It only works for HTTPS functions for now, but my guess is that they will soon support sending database events.

**Comment by urish** [comment]
firebase-server does not support functions, and is not likely to support them in the future. You can check out the emulator mentioned by Scott.
